# Generated by Django 6.0.5 on 2026-06-30 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_otprecord_verification_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
            ],
            options={
                'verbose_name': 'App User',
                'verbose_name_plural': 'App Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('owners.owner',),
        ),
        migrations.CreateModel(
            name='HostelOwner',
            fields=[
            ],
            options={
                'verbose_name': 'Hostel Owner',
                'verbose_name_plural': 'Hostel Owners',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('owners.owner',),
        ),
    ]
