# Generated by Django 6.0.5 on 2026-06-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_appuser_hostelowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='signup_source',
            field=models.CharField(choices=[('admin_panel', 'Admin Panel'), ('app', 'App')], default='app', max_length=20),
        ),
    ]
