# Generated by Django 6.0.5 on 2026-06-30 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('hostels', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hostel',
            field=models.ForeignKey(db_column='hostel_id', on_delete=django.db.models.deletion.CASCADE, related_name='hostel_bookings', to='hostels.hostel'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rooms.room'),
        ),
    ]
