# Generated by Django 6.0.5 on 2026-06-30 08:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostels', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='media_uploads/')),
                ('category', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('document', 'Document')], default='photo', max_length=20)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=255)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(blank=True, db_column='hostel_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='hostels.hostel')),
                ('room', models.ForeignKey(blank=True, db_column='room_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='rooms.room')),
            ],
            options={
                'db_table': 'media_items',
                'ordering': ['order_index'],
            },
        ),
    ]
