# Generated by Django 6.0.5 on 2026-06-30 08:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100)),
                ('sharing_type', models.CharField(max_length=20)),
                ('capacity', models.IntegerField(default=1)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_beds', models.IntegerField(default=0)),
                ('has_attached_bathroom', models.BooleanField(default=False)),
                ('is_ac', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostel', models.ForeignKey(db_column='hostel_id', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostels.hostel')),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['room_name'],
            },
        ),
    ]
