# Generated by Django 3.2.25 on 2026-02-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='One OTP record per email. Overwritten on resend.', max_length=254, unique=True)),
                ('otp_hash', models.CharField(help_text='SHA-256 hash of the 6-digit OTP code.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='OTP becomes invalid after this time.')),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('send_count', models.PositiveSmallIntegerField(default=1)),
                ('first_send_at', models.DateTimeField(help_text='Start of the current hourly rate-limit window.')),
            ],
            options={
                'verbose_name': 'OTP Record',
                'ordering': ['-created_at'],
            },
        ),
    ]
