# Generated by Django 3.2.25 on 2026-02-20 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('hostel_type', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('mixed', 'Mixed / Co-ed')], db_index=True, default='mixed', max_length=10)),
                ('price_per_month', models.DecimalField(db_index=True, decimal_places=2, max_digits=8)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('amenities', models.TextField(blank=True, default='', help_text='Comma-separated list of amenities: WiFi,AC,Meals,Parking')),
                ('total_rooms', models.PositiveSmallIntegerField(default=1)),
                ('available_rooms', models.PositiveSmallIntegerField(default=1)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HostelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hostels/images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hostels.hostel')),
            ],
        ),
        migrations.AddIndex(
            model_name='hostel',
            index=models.Index(fields=['city', 'hostel_type'], name='hostels_hos_city_8c679d_idx'),
        ),
        migrations.AddIndex(
            model_name='hostel',
            index=models.Index(fields=['city', 'price_per_month'], name='hostels_hos_city_077bf2_idx'),
        ),
    ]
