# Generated by Django 6.0.5 on 2026-06-30 08:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('hostel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('google_maps_url', models.CharField(blank=True, max_length=500, null=True)),
                ('gender_type', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('mixed', 'Mixed / Co-ed')], db_index=True, default='mixed', max_length=20)),
                ('total_floors', models.IntegerField(default=1)),
                ('total_rooms', models.IntegerField(default=1)),
                ('total_beds', models.IntegerField(default=1)),
                ('occupancy_types', models.JSONField(default=list)),
                ('description', models.TextField(blank=True, null=True)),
                ('rules', models.TextField(blank=True, null=True)),
                ('check_in_policy', models.CharField(blank=True, max_length=255, null=True)),
                ('check_out_policy', models.CharField(blank=True, max_length=255, null=True)),
                ('amenities', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'hostels',
                'ordering': ['-created_at'],
            },
        ),
    ]
